name: MultiModalStory
channels:
  - conda-forge
  - anaconda
dependencies:
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_contrib_core
  - jupyter_contrib_nbextensions
  - matplotlib
  - nb_conda
